[package]
name = "interject"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10.9"
thiserror = "2.0.21"
ureq = { version = "3.2.1", features = ["json"] }
